String StartButton = "Start", QuitButton = "Quit";
PFont font;
PImage Cake, BigButtonImage, BigButtonImageII, smollButtonI, smollButtonII, smollButtonIII;
int appWidth, appHeight, size;
boolean OS_On=false, splashScreenStart=false;
color Blue=#0052FF, Red=#FF3300, Black=#000000, White=#FFFFFF, DarkRed=#270101;
float startButtonX, startButtonY, startButtonWidth, startButtonHeight;
float centerX, centerY;
float backgroundX, backgroundY, backgroundWidth, backgroundHeight;
float rectIX, rectIY, rectIWidth, rectIHeight;
float rectIIX, rectIIY, rectIIWidth, rectIIHeight;
float rectIIIX, rectIIIY, rectIIIWidth, rectIIIHeight; 
float rectIVX, rectIVY, rectIVWidth, rectIVHeight;
float rectVX, rectVY, rectVWidth, rectVHeight;
float rectVIX, rectVIY, rectVIWidth, rectVIHeight; 
float rectVIIX, rectVIIY, rectVIIWidth, rectVIIHeight;
float rectVIIIX, rectVIIIY, rectVIIIWidth, rectVIIIHeight;
float rectIXX, rectIXY, rectIXWidth, rectIXHeight;
float buttonIX, buttonIY, buttonIW, buttonIH;
float buttonIIX, buttonIIY, buttonIIW, buttonIIH;
float quitX, quitY, quitW, quitH; 
float buttonIIIX, buttonIIIY, buttonIIIW, buttonIIIH;
float smollButtonIX, smollButtonIY, smollButtonIW, smollButtonIH;
float smollButtonIIX, smollButtonIIY, smollButtonIIW, smollButtonIIH;
float smollButtonIIIX, smollButtonIIIY, smollButtonIIIW, smollButtonIIIH;
float smollButtonIVX, smollButtonIVY, smollButtonIVW, smollButtonIVH;
float smollButtonVX, smollButtonVY, smollButtonVW, smollButtonVH;
float wideButtonIX, wideButtonIY, wideButtonIW, wideButtonIH;
float wideButtonIIX, wideButtonIIY, wideButtonIIW, wideButtonIIH;
float tallButtonIX, tallButtonIY, tallButtonIW, tallButtonIH;
float tallButtonIIX, tallButtonIIY, tallButtonIIW, tallButtonIIH;
